name: Build CRP Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install pkg-config
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Install
        run: cmake --install build --config Release --prefix ${{ github.workspace }}/install
      - name: Upload library and pkg-config file
        uses: actions/upload-artifact@v4
        with:
          name: crp-${{ runner.os }}
          path: |
            install/lib/*
            install/lib/pkgconfig/crp.pc
